type User {
    id: ID!
    name: String
    email: String
    phone: String
    categories: [Category]
}

type Category {
    id: ID!
    name: String
    images: String
    users: [User]
    products: [Product]
}

type Product {
    id: ID!
    title: String
    quantity: Int
    description: String
    price: Float
    category: Category
}

# Queries
type Query {
    users: [User]
    categories: [Category]
    products(orderByPriceAsc: Boolean = false): [Product]
    productsByCategory(categoryId: ID!): [Product]
}

# Mutations
input UserInput {
    id: ID
    name: String
    email: String
    password: String
    phone: String
}

input CategoryInput {
    id: ID
    name: String
    images: String
}

input ProductInput {
    id: ID
    title: String
    quantity: Int
    description: String
    price: Float
    categoryId: ID
}

type Mutation {
    upsertUser(input: UserInput!): User
    deleteUser(id: ID!): Boolean

    upsertCategory(input: CategoryInput!): Category
    deleteCategory(id: ID!): Boolean

    upsertProduct(input: ProductInput!): Product
    deleteProduct(id: ID!): Boolean
}
